# Generated by Django 4.1 on 2022-08-13 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('key_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(default='')),
                ('input_file', models.FileField(upload_to='input')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='output')),
            ],
        ),
    ]
